### ISSUE TITLE
livelint doesn't work with auth-provider OIDC

### ISSUE THREAD

**Issue by belov38** [bespinian/livelint#90]
livelint doesn't work with auth-provider OIDC
```
# livelint
failed to start livelint: error creating k8s client set: no Auth Provider found for name "oidc"
```

My kubeconfig:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://api.k8s-dev.####
  name: api.k8s-dev..####
contexts:
- context:
    cluster: api.k8s-dev..####
    namespace: .####
    user: admin1-api.k8s-dev..####
  name: admin1-api.k8s-dev..####
current-context: admin1-api.k8s-dev..####
kind: Config
preferences: {}
users:
- name: api.k8s-dev..####
  user:
    auth-provider:
      config:
        client-id: kubeconfig-generator
        client-secret: .####
        id-token: .####
        idp-issuer-url: https://dex.k8s-dev..####
        refresh-token: .####
      name: oidc
```
